let initialPoem = [
    {
        "text": "Hi",
        "type": "slide",
        "start": "0s",
        "duration": "1s",
        "from": {x: 300, y: 600,  scale: 20},
        "to": {x:300, y: 20, scale: 1},
        "easing": "cubic-bezier(0.12, 0, 0.39, 0)",
        "font": "Optima",
        "easing": "linear",
        "color": "#73CE72F0",
    },
    {
        "text": "class",
        "type": "slide",
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)", // css easing function
        "start": "3s", 
        "duration": "1s",
        "from": {x:900, y: 30},
        "to": {x:340, y: 30},
        "background": "#000000", // background color, defaults to not changing from the previous background color
        "font": "Futura",
        "style": {color: '#CCF4CBF0'}, // any other css, applied on top of whatever this is 
    },
    {
        "text": "I'm",
        "type": "slide",
        "start": "1s",
        "duration": "1s",
        "color": "#CCF4CBF0",
        "from": {x: 0, y: 0, scale: 5},
        "to": {x: 300, y: 50, scale: 1},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
    },
    {
        "text": "Alex",
        "type": "slide",
        "start": "2s",
        "duration": "1s",
        "from": {x: 1000, y: 1000, scale: 9},
        "to": {x: 300, y: 100, scale: 1},
        "font": "Gill Sans",
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
    },
    {
        "text": "called",
        "type": "slide",
        "start": "3s", 
        "duration": "1s", 
        "from": {x: -100, y: 75},
        "to": {x: 240, y: 75},
        "color": "#FFFFFF",// text color
        "background": "#000000", // background color, defaults to not changing from the previous background color
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        // "keyframes":  { transform: "rotate(0) scale(100%)" }, // overwrite the other animations
        "timing": {duration: 1000, iterations: 1, fill: "forwards"},
    },
    {
        "text": "I'm",
        "type": "slide",
        "start": "5s",
        "duration": "0.7s",
        "from": {x: 300, y: 50},
        "to": {x: 300, y: 125},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
    },
    {
        "text": "interested in",
        "type": "slide",
        "start": "previous",
        "duration": "0.7s",
        "from": {x: 300, y: 125},
        "to": {x: 300, y: 150},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"}, // center the word using CSS tricks
    },
    {
        "text": "exploring",
        "type": "slide",
        "start": "7.2s",
        "duration": "0.7s",
        "from": {x: 300, y: 150},
        "to":   {x: 300, y: 175},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"}, // center the word using CSS tricks
    },
    {
        "text": "the applications of poetry",
        "type": "slide",
        "start": "8.5s",
        "duration": "6.2s",
        "from": {x: 1000, y: 175},
        "to":   {x: -300, y: 175},
        "easing": "linear",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"}, // center the word using CSS tricks
    },
    {
        "text": "and programming",
        "type": "slide",
        "start": "11s",
        "duration": "10s",
        "from": {x: 1000, y: 175},
        "to":   {x: -300, y: 175},
        "easing": "linear",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"}, // center the word using CSS tricks
    },
    {
        "text": "art",
        "type": "slide",
        "start": "15s",
        "duration": "6s",
        "from": {x: 1000, y: 175},
        "to":   {x: -300, y: 175},
        "easing": "linear",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"}, // center the word using CSS tricks
    },
    {
        "text": "and technology",
        "type": "slide",
        "start": "16s",
        "duration": "9s",
        "from": {x: 1000, y: 175},
        "to":   {x: -300, y: 175},
        "easing": "linear",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"}, // center the word using CSS tricks
    },
    {
        "text": "language",
        "type": "slide",
        "start": "23.5s",
        "duration": "0.25s",
        "from":   {x: 300, y: 175},
        "to":   {x: 300, y: 200},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"}, // center the word using CSS tricks
    },
    {
        "text": "that",
        "type": "slide",
        "start": "previous",
        "duration": "0.25s",
        "from":   {x: 300, y: 200},
        "to":   {x: 300, y: 225},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"}, // center the word using CSS tricks
    },
    {
        "text": "moves",
        "type": "slide",
        "start": "previous",
        "duration": "0.25s",
        "from": {x: 300, y: 225},
        "to":   {x: 300, y: 250},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"}, // center the word using CSS tricks
    },

    // second language that moves
    {
        "text": "that",
        "type": "slide",
        "start": "25s",
        "duration": "0.25s",
        "from":   {x: 300, y: 225},
        "to":     {x: 370, y: 225},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"}, // center the word using CSS tricks
    },
    {
        "text": "moves",
        "type": "slide",
        "start": "25s",
        "duration": "0.25s",
        "from": {x: 340, y: 250},
        "to":   {x: 370, y: 250},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"}, // center the word using CSS tricks
    },
    
    // third that moves
    {
        "text": "that",
        "type": "slide",
        "start": "26s",
        "duration": "0.25s",
        "from":   {x: 300, y: 225},
        "to":     {x: 230, y: 225},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"}, // center the word using CSS tricks
    },
    {
        "text": "moves",
        "type": "slide",
        "start": "26s",
        "duration": "0.25s",
        "from": {x: 340, y: 250},
        "to":   {x: 230, y: 250},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)", "font-style": "italic"}, // center the word using CSS tricks and make italic
    },

    {
        "text": "language",
        "type": "slide",
        "start": "27s",
        "duration": "0.5s",
        "from":   {x: 300, y: 200},
        "to":     {x: 300, y: 275},
        "easing": "linear",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"}, // center the word using CSS tricks
    },

    // second row of moves
    {
        "text": "moves",
        "type": "slide",
        "start": "28s",
        "duration": "0.5s",
        "from": {x: 230, y: 250},
        "to":   {x: 230, y: 300},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"},
    },
    {
        "text": "moves",
        "type": "slide",
        "start": "28s",
        "duration": "0.5s",
        "from":  {x: 300, y: 250},
        "to":    {x: 300, y: 300},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"},
    },
    {
        "text": "moves",
        "type": "slide",
        "start": "28s",
        "duration": "0.5s",
        "from": {x: 370, y: 250},
        "to":   {x: 370, y: 300},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"},
    },

    {
        "text": "with",
        "type": "slide",
        "start": "29s",
        "duration": "0.25s",
        "from": {x: 370, y: 300},
        "to":   {x: 370, y: 325},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"},
    },

    {
        "text": "you",
        "type": "slide",
        "start": "30s",
        "duration": "0.5s",
        "from":   {x: 370, y: 325},
        "to":     {x: 300, y: 325},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"},
    },

    {
        "text": "to",
        "type": "slide",
        "start": "31s",
        "duration": "0.5s",
        "from":   {x: 370, y: 325},
        "to":     {x: 230, y: 325},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"},
    },

    {
        "text": "move",
        "type": "slide",
        "start": "32s",
        "duration": "1s",
        "from": {x: 230, y: 300},
        "to":   {x: 230, y: 350},
        "easing": "linear",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"},
    },
    // {
    //     "text": "to",
    //     "type": "slide",
    //     "start": "33.5s",
    //     "duration": "0.5s",
    //     "from": {x: 300, y: 350},
    //     "to":   {x: 230, y: 350},
    //     "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
    //     "font": "Futura",
    //     "style": {"transform": "translateX(-50%)"},
    // },
    {
        "text": "too",
        "type": "slide",
        "start": "33.5s",
        "duration": "0.5s",
        "from": {x: 230, y: 325},
        "to":   {x: 230, y: 375},
        "easing": "cubic-bezier(0.33, 1, 0.68, 1)",
        "font": "Futura",
        "style": {"transform": "translateX(-50%)"},
    },

    // {
    //     "text": "you",
    //     "type": "slide",
    //     "start": "33.5s",
    //     "duration": "1s",
    //     "from": {x: 300, y: 350},
    //     "to":   {x: 300, y: 325},
    //     "easing": "linear",
    //     "font": "Futura",
    //     "style": {"transform": "translateX(-50%)"},
    // },
]